<!--Awesome-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
<!--bootstrap-->
<link href="css/bootstrap.css" rel="stylesheet" type="text/css"/>
<!--jQuery UI-->
<link href="css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<link href="css/jquery-ui.theme.css" rel="stylesheet" type="text/css"/>
<!--external css, like plugins ...-->
<link href="css/animation.css" rel="stylesheet" type="text/css"/>
<link href="css/form-validation.css" rel="stylesheet" type="text/css"/>
<link href="css/style.css" rel="stylesheet" type="text/css"/>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js" type="text/javascript"></script>
<script src="js/popper.js" type="text/javascript"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
<script src="js/sweetalert.js" type="text/javascript"></script>
<!--<script src="js/disabledRightClickAndCtrl.js" type="text/javascript"></script>-->
<script src="js/jquery.validate.min.js" type="text/javascript"></script>
<script src="js/main.js" type="text/javascript"></script>
<!--Jquery BlockUI-->
<script src="js/jquery.blockUI.js"></script>
